"use client";

import { motion, AnimatePresence } from "framer-motion";
import {
  ShieldCheck,
  ShieldAlert,
  AlertTriangle,
  Download,
  Printer,
  X,
  FileCheck,
  Hash,
  Clock,
  Award,
  CheckCircle2,
} from "lucide-react";
import type { AnalysisResult } from "@/lib/types";
import { formatDuration } from "@/lib/utils";

interface ForensicReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: AnalysisResult;
}

export default function ForensicReportModal({
  isOpen,
  onClose,
  result,
}: ForensicReportModalProps) {
  if (!isOpen) return null;

  const isHuman = result.verdict === "human";
  const isCloned = result.verdict === "cloned";

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(result, null, 2));
    const downloadAnchor = document.createElement("a");
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `voxguard_forensic_report_${result.id}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 overflow-y-auto bg-slate-950/80 backdrop-blur-md print:p-0 print:bg-white">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 10 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 10 }}
          className="relative w-full max-w-4xl max-h-[90vh] overflow-y-auto bg-slate-900 border border-cyan-500/30 rounded-2xl shadow-2xl p-6 sm:p-8 text-slate-100 print:max-h-none print:overflow-visible print:border-none print:shadow-none print:bg-white print:text-black"
        >
          {/* Action Bar (Hidden in Print) */}
          <div className="flex items-center justify-between pb-6 mb-6 border-b border-white/[0.08] print:hidden">
            <div className="flex items-center gap-2">
              <FileCheck className="text-cyan-400" size={22} />
              <span className="text-sm font-bold uppercase tracking-wider text-white">
                Official Voice Forensic Examination Certificate
              </span>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handlePrint}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/[0.06] hover:bg-white/[0.12] text-xs font-medium text-slate-200 transition-colors cursor-pointer"
                title="Print or Save PDF"
              >
                <Printer size={14} />
                Print / Save PDF
              </button>
              <button
                onClick={handleDownloadJSON}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-cyan-500/20 hover:bg-cyan-500/30 border border-cyan-500/40 text-xs font-medium text-cyan-300 transition-colors cursor-pointer"
                title="Export RAW JSON Audit Log"
              >
                <Download size={14} />
                Export JSON
              </button>
              <button
                onClick={onClose}
                className="p-1.5 rounded-lg bg-white/[0.04] hover:bg-white/[0.08] text-slate-400 hover:text-white transition-colors cursor-pointer ml-2"
              >
                <X size={18} />
              </button>
            </div>
          </div>

          {/* Certificate Header */}
          <div className="text-center pb-6 border-b border-white/[0.08] print:border-black/20">
            <div className="inline-flex items-center justify-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 text-xs font-mono font-semibold mb-3 print:border-black/30 print:text-black">
              <Award size={14} /> VOXGUARD FORENSIC AUDIT SPECIFICATION v2.4
            </div>
            <h1 className="text-2xl sm:text-3xl font-black text-white uppercase tracking-wider print:text-black">
              Acoustic Integrity &amp; Clone Verification Audit
            </h1>
            <p className="text-xs text-slate-400 mt-1 print:text-slate-600">
              Generated by VoxGuard Multi-Stage Audio Forensic Engine &bull; Smart India Hackathon SIH26104
            </p>
          </div>

          {/* Evidence Meta & Case File Details */}
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 my-6 p-4 rounded-xl bg-slate-950/60 border border-white/[0.05] text-xs font-mono print:bg-slate-50 print:border-black/20 print:text-black">
            <div>
              <span className="text-slate-500 block text-[10px] uppercase">Case Report ID</span>
              <span className="font-bold text-cyan-300 print:text-black">{result.id}</span>
            </div>
            <div>
              <span className="text-slate-500 block text-[10px] uppercase">Timestamp (UTC)</span>
              <span className="text-slate-300 print:text-black">{new Date(result.timestamp).toUTCString()}</span>
            </div>
            <div>
              <span className="text-slate-500 block text-[10px] uppercase">Examined Audio File</span>
              <span className="text-slate-300 truncate block print:text-black" title={result.fileName}>
                {result.fileName}
              </span>
            </div>
            <div>
              <span className="text-slate-500 block text-[10px] uppercase">Duration &amp; Sample Rate</span>
              <span className="text-slate-300 print:text-black">
                {formatDuration(result.audio.duration)} &bull; {result.audio.sampleRate} Hz
              </span>
            </div>
          </div>

          {/* Cryptographic Proof Hash */}
          <div className="mb-6 p-3 rounded-lg bg-slate-950/40 border border-white/[0.04] flex items-center justify-between text-xs font-mono print:bg-slate-100 print:border-black/10">
            <div className="flex items-center gap-2 overflow-hidden">
              <Hash size={14} className="text-cyan-400 shrink-0 print:text-black" />
              <span className="text-slate-400 shrink-0">SHA-256 Digest:</span>
              <span className="text-cyan-300/90 truncate print:text-black">{result.audio.sha256}</span>
            </div>
            <span className="text-[10px] text-emerald-400 flex items-center gap-1 shrink-0 ml-2 font-semibold">
              <CheckCircle2 size={12} /> Verified Chain of Custody
            </span>
          </div>

          {/* Core Judicial Finding & Verdict Banner */}
          <div
            className={`p-5 rounded-xl border flex flex-col sm:flex-row items-center justify-between gap-4 mb-6 ${
              isHuman
                ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-300 print:border-emerald-700"
                : isCloned
                ? "bg-red-500/10 border-red-500/30 text-red-300 print:border-red-700"
                : "bg-amber-500/10 border-amber-500/30 text-amber-300 print:border-amber-700"
            }`}
          >
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-xl bg-slate-950/50 print:bg-white">
                {isHuman ? (
                  <ShieldCheck size={36} className="text-emerald-400" />
                ) : isCloned ? (
                  <ShieldAlert size={36} className="text-red-400" />
                ) : (
                  <AlertTriangle size={36} className="text-amber-400" />
                )}
              </div>
              <div>
                <div className="text-[10px] uppercase font-bold tracking-widest text-slate-400">
                  Forensic Verdict Classification
                </div>
                <div className="text-xl sm:text-2xl font-black uppercase tracking-wider text-white print:text-black">
                  {result.verdict === "human"
                    ? "Authentic Human Voice"
                    : result.verdict === "cloned"
                    ? "Synthetic AI Voice Clone"
                    : "Suspicious / Inconclusive Signal"}
                </div>
                <p className="text-xs text-slate-300 mt-0.5 print:text-slate-700 max-w-xl">
                  {result.summary}
                </p>
              </div>
            </div>

            <div className="text-right shrink-0">
              <div className="text-[10px] uppercase font-bold text-slate-400">Confidence Rating</div>
              <div className="text-3xl font-black font-mono text-white print:text-black">
                {Math.round(result.confidence * 100)}%
              </div>
              <div className="text-[10px] font-mono text-slate-400">
                Risk: <span className="uppercase font-bold text-white print:text-black">{result.riskLevel}</span>
              </div>
            </div>
          </div>

          {/* Primary Acoustic Parameters Table */}
          <div className="my-6">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300 mb-3 print:text-black">
              Forensic Signal Parameter Measurements
            </h3>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs border-collapse font-mono print:text-black">
                <thead>
                  <tr className="border-b border-white/[0.08] text-slate-500 print:border-black/20">
                    <th className="pb-2">Parameter</th>
                    <th className="pb-2">Measured Value</th>
                    <th className="pb-2">Natural Speech Baseline</th>
                    <th className="pb-2">Evaluation</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/[0.04] print:divide-black/10">
                  <tr>
                    <td className="py-2 text-slate-300 print:text-black">Pitch Jitter (PPQ)</td>
                    <td className="py-2 font-bold text-cyan-300 print:text-black">
                      {result.measurements.pitchJitterPercent.toFixed(2)}%
                    </td>
                    <td className="py-2 text-slate-400 print:text-slate-600">0.50% &ndash; 2.50%</td>
                    <td className="py-2 text-slate-300 print:text-black">
                      {result.measurements.pitchJitterPercent < 0.25 ? "Synthetically Rigid (Deepfake)" : "Natural Glottal Jitter"}
                    </td>
                  </tr>
                  <tr>
                    <td className="py-2 text-slate-300 print:text-black">Vocal Shimmer (APQ)</td>
                    <td className="py-2 font-bold text-cyan-300 print:text-black">
                      {result.measurements.vocalShimmerPercent.toFixed(2)}%
                    </td>
                    <td className="py-2 text-slate-400 print:text-slate-600">1.50% &ndash; 5.00%</td>
                    <td className="py-2 text-slate-300 print:text-black">
                      {result.measurements.vocalShimmerPercent < 0.8 ? "Vocoder Over-smoothing" : "Normal Amplitude Variance"}
                    </td>
                  </tr>
                  <tr>
                    <td className="py-2 text-slate-300 print:text-black">Spectral Flatness (Entropy)</td>
                    <td className="py-2 font-bold text-cyan-300 print:text-black">
                      {result.measurements.spectralFlatness.toFixed(4)}
                    </td>
                    <td className="py-2 text-slate-400 print:text-slate-600">0.0050 &ndash; 0.0800</td>
                    <td className="py-2 text-slate-300 print:text-black">
                      {result.measurements.spectralFlatness < 0.002 ? "Hyper-Tonal Vocoder Artifact" : "Standard Formant Distribution"}
                    </td>
                  </tr>
                  <tr>
                    <td className="py-2 text-slate-300 print:text-black">Harmonic-to-Noise Ratio (HNR)</td>
                    <td className="py-2 font-bold text-cyan-300 print:text-black">
                      {result.measurements.harmonicToNoiseRatioDb.toFixed(1)} dB
                    </td>
                    <td className="py-2 text-slate-400 print:text-slate-600">12.0 &ndash; 24.0 dB</td>
                    <td className="py-2 text-slate-300 print:text-black">
                      {result.measurements.harmonicToNoiseRatioDb > 26 ? "Artificial Noise Floor Suppression" : "Organic Aspiration Floor"}
                    </td>
                  </tr>
                  <tr>
                    <td className="py-2 text-slate-300 print:text-black">Neural Cutoff Filter</td>
                    <td className="py-2 font-bold text-cyan-300 print:text-black">
                      {result.measurements.vocoderCutoffHz ? `${(result.measurements.vocoderCutoffHz / 1000).toFixed(1)} kHz` : "None"}
                    </td>
                    <td className="py-2 text-slate-400 print:text-slate-600">&gt; 20.0 kHz (Full Band)</td>
                    <td className="py-2 text-slate-300 print:text-black">
                      {result.measurements.vocoderCutoffHz ? "Neural Resampling Low-Pass Cutoff" : "Full-Band Spectral Envelope"}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Examiner Attestation & Sign-off Block */}
          <div className="mt-8 pt-6 border-t border-white/[0.08] grid grid-cols-1 sm:grid-cols-2 gap-6 print:border-black/20 text-xs">
            <div>
              <span className="text-[10px] uppercase text-slate-500 font-bold block mb-1">
                Forensic Engine Configuration
              </span>
              <p className="text-slate-400 print:text-slate-700 leading-relaxed font-mono text-[11px]">
                Inference Engine: {result.modelMetrics.inferenceEngine} &bull; Architecture: {result.modelMetrics.detectorArchitecture} &bull; Processing Time: {result.modelMetrics.processingTimeMs}ms
              </p>
            </div>
            <div className="sm:text-right">
              <span className="text-[10px] uppercase text-slate-500 font-bold block mb-3">
                Digital Examination Attestation
              </span>
              <div className="inline-block border-b border-white/40 print:border-black w-48 mb-1"></div>
              <p className="font-mono text-[10px] text-slate-400 print:text-black">
                Automated Cryptographic Seal &bull; SIH26104 Compliance
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
